### ISSUE TITLE
translate

### ISSUE THREAD

**Issue by RedTeaBaby** [kochkaev/seasons-challenges#1]
need Chinese translate！！！！！

**Comment by kochkaev** [comment]
'Kay, I'll try to write it, but translate may will be not so correct.

**Comment by RedTeaBaby** [comment]
In fact, I have already translated it, but I don't know how to upload it to you. Should I directly package the jar for you or not?? I need you to give me permission for a project

**Comment by RedTeaBaby** [comment]
I'm sorry for making this decision without permission. I was worried that I wouldn't be able to contact you, so I asked my friends. They taught me how to use fork to upload files, and I have no intention of infringing. I just want to use your mod in my modpack. I'm a beginner in this industry and I'm not sure about many things. If it causes any trouble for you, please contact me!!! I'm really sorry

**Comment by RedTeaBaby** [comment]
Additionally, I encountered a crash while adjusting the weather to Stormy using instructions, and I am unsure of the reason. I hope it can be fixed

**Comment by RedTeaBaby** [comment]
In the water, entering the water during a storm can cause collapse

**Comment by kochkaev** [comment]
Thanks a lot! You may open the pull request to push your translate to my repository with preservation of your copyright. 
As for the error you found, can you describe it in more detail?

**Comment by kochkaev** [comment]
I think I've figured out what crash you're talking about. It was fixed in [Seasons API  1.2-BETA-2](https://github.com/kochkaev/seasons-api/releases/tag/1.2-BETA-2)

**Comment by RedTeaBaby** [comment]
I understand, the bug has been fixed, and 
[DefaultTXTLangZH.zip](https://github.com/user-attachments/files/18079846/DefaultTXTLangZH.zip)

I don't know how to use GitHub. However, with the help of a friend, I forked your project and uploaded the source file. If possible, I will try to submit a Chinese translation directly here for you to update easily!

**Comment by kochkaev** [comment]
Thanks a lot for the contribution! I was merge your fork with this repository, your  translation will be able in the next update.
